os: Windows Server 2012

version: '{build}'

init:
  - git config --global core.autocrlf true

build_script:
  # JNA fix according to https://github.com/sbt/io/issues/110
  - mvn -Djna.nosys=true package --batch-mode -DskipTest

test_script:
  # JNA fix according to https://github.com/sbt/io/issues/110
  - mvn -Djna.nosys=true verify --batch-mode
